# To execute this docker-compose yml file use `docker-compose -f <file_name> up`
# Add the `-d` flag at the end for detached execution
version: '2'
services:
  chrome:
    image: selenium/node-chrome-debug:3.141.59
    volumes:
      - /Users/wanghaihong/selenium_node1/dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    ports:
      - "49338:5900"
    environment:
      HUB_HOST: selenium-hub
      NODE_MAX_INSTANCES: 5
      NODE_MAX_SESSION: 5

  chrome2:
    image: selenium/node-chrome-debug:3.141.59
    volumes:
      - /Users/wanghaihong/selenium_node2/dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    ports:
      - "49339:5900"
    environment:
      HUB_HOST: selenium-hub
      NODE_MAX_INSTANCES: 5
      NODE_MAX_SESSION: 5

  selenium-hub:
    image: selenium/hub:3.141.59
    container_name: selenium-hub
    ports:
      - "4444:4444"
